# -*- coding: utf-8 -*-
"""hack.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XJ-zOLCQbO4DaYiwVygPlxL5T4SMfB0t
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import Perceptron
import pandas as pd
import imblearn
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn import svm
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import rbf_kernel
from sklearn.linear_model import LogisticRegression
import pickle

filepath = r'./processed.cleveland.csv'

df_bin = pd.read_csv(filepath)
data_np = df_bin.to_numpy()  #convert to numpy

row, col = data_np.shape
data_labels = data_np[:,col - 1]
data = data_np[:,0:col - 1]

def get_class_data(x, data_labels): ##class 1: label 0, no default
                                    ##class 2: label 1, default
    class_1 = x[data_labels == 0]
    class_2 = x[data_labels == 1]
    class_3 = x[data_labels == 2]
    class_4 = x[data_labels == 3]
    class_5 = x[data_labels == 4]


    return class_1, class_2, class_3, class_4, class_5

class_1, class_2, class_3, class_4, class_5 = get_class_data(data, data_labels)

data_labels = data_labels.astype('int')
for i in range(len(data_labels)):
    if(data[i,11] != '?'):
        data[i,11] = float(data[i,11])
    else:
        data[i,11] =  0.0

for i in range(len(data_labels)):
    if(data[i,12] != '?'):
        data[i,12] = float(data[i,12])
    else:
        data[i,12] =  0.0

oversample = SMOTE()
x, y = oversample.fit_resample(data, data_labels)

cl1, cl2, cl3, cl4, cl5 = get_class_data(x,y)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

scalar_  = StandardScaler() ##use pickle to save this object scalar_
scalar_.fit(x_train)
x_train = scalar_.transform(x_train)
x_test = scalar_.transform(x_test)
with open('hackathon.pkl', 'wb') as file:
    pickle.dump(scalar_, file)

pca = PCA(7) ##7, C = 10/20
pca.fit(x_train)
x_train = pca.transform(x_train) ##use pickle to save this object pca
x_test = pca.transform(x_test)
with open('pca.pkl', 'wb') as file:
    pickle.dump(pca, file)


classifier = svm.SVC(kernel = "rbf", C = 10) ##use pickle to save this object classifier_
classifier.fit(x_train,y_train)
with open('classifier.pkl', 'wb') as file:
    pickle.dump(classifier, file)

#w_ = classifier.coef_
#w_0 = classifier.intercept_
#sv_ = classifier.support_vectors_
#y_pred = classifier.predict(x)
accuracy = classifier.score(x_train, y_train)
acc_test = classifier.score(x_test,y_test)

print(accuracy)
print(acc_test)